spring.application.name=catalogo

# Configuración de springdoc (OpenAPI)
springdoc.api-docs.path=/v3/api-docs
# La UI estará disponible en /swagger-ui.html (o /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging corregido
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
server-port=8082